2025-04-14 06:41:08,325 - INFO - Processing dataset from ../../Datasets/20BN_Jester_Dataset/train_subset/
2025-04-14 06:41:08,325 - INFO - Saving results to ../../Datasets/20BN_Jester_Dataset/train_subset_preprocessed/
2025-04-14 06:41:08,325 - INFO - Found 10 sample directories
2025-04-14 06:41:08,325 - INFO - Processing batch 1/1 (10 samples)
2025-04-14 06:41:08,971 - CRITICAL - Exception in initializer:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 235, in _process_worker
    initializer(*initargs)
  File "/Users/koh/Research/Codes/Gesture_Customization_github/preprocess_2.py", line 255, in init_worker
    warnings.filterwarnings('ignore')
    ^^^^^^^^
UnboundLocalError: cannot access local variable 'warnings' where it is not associated with a value
2025-04-14 06:41:08,987 - CRITICAL - Exception in initializer:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 235, in _process_worker
    initializer(*initargs)
  File "/Users/koh/Research/Codes/Gesture_Customization_github/preprocess_2.py", line 255, in init_worker
    warnings.filterwarnings('ignore')
    ^^^^^^^^
UnboundLocalError: cannot access local variable 'warnings' where it is not associated with a value
2025-04-14 06:41:08,988 - CRITICAL - Exception in initializer:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 235, in _process_worker
    initializer(*initargs)
  File "/Users/koh/Research/Codes/Gesture_Customization_github/preprocess_2.py", line 255, in init_worker
    warnings.filterwarnings('ignore')
    ^^^^^^^^
UnboundLocalError: cannot access local variable 'warnings' where it is not associated with a value
2025-04-14 06:41:08,993 - CRITICAL - Exception in initializer:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 235, in _process_worker
    initializer(*initargs)
  File "/Users/koh/Research/Codes/Gesture_Customization_github/preprocess_2.py", line 255, in init_worker
    warnings.filterwarnings('ignore')
    ^^^^^^^^
UnboundLocalError: cannot access local variable 'warnings' where it is not associated with a value
2025-04-14 06:44:43,127 - INFO - Processing dataset from ../../Datasets/20BN_Jester_Dataset/train_subset/
2025-04-14 06:44:43,127 - INFO - Saving results to ../../Datasets/20BN_Jester_Dataset/train_subset_preprocessed/
2025-04-14 06:44:43,127 - INFO - Found 10 sample directories
2025-04-14 06:44:43,127 - INFO - Processing batch 1/1 (10 samples)
2025-04-14 06:44:52,146 - INFO - Processed 10 samples, 10 successful
2025-04-14 06:50:16,984 - INFO - Processing dataset from ../../Datasets/20BN_Jester_Dataset/train_subset/
2025-04-14 06:50:16,984 - INFO - Saving results to ../../Datasets/20BN_Jester_Dataset/train_subset_preprocessed/
2025-04-14 06:50:16,984 - INFO - Found 10 sample directories
2025-04-14 06:50:16,984 - INFO - Processing batch 1/1 (10 samples)
2025-04-14 06:50:25,254 - INFO - Processed 10 samples, 10 successful
